---
- name: Install load balancers
  hosts: lb
  become: yes
  tasks:
    - name: Install nginx-extras (includes vts module)
      apt:
        name: nginx-extras
        state: present
        update_cache: yes

    - name: Copy nginx configuration for load balancing
      copy:
        src: files/nginx_lb.conf
        dest: /etc/nginx/nginx.conf
      notify: restart nginx

    - name: Ensure vts module is loaded
      lineinfile:
        path: /etc/nginx/nginx.conf
        insertbefore: '^http {'
        line: 'load_module /usr/lib/nginx/modules/ngx_http_vhost_traffic_status_module.so;'
      notify: restart nginx

    - name: Start nginx
      command: nginx
      args:
        creates: /var/run/nginx.pid

  handlers:
    - name: restart nginx
      command: nginx -s reload
